[package]
name = "asm2test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
lazy_static = "1.4.0"
pl-lens = "1.0.1"
regex = "1.10.2"
